version: '3'
services:
  bot:
    image: ghcr.io/ukenn2112/bangumi-telegram-bot
    container_name: BangumiTelegramBot-bot
    restart: always
    command: pipenv run python3 main.py
    networks:
      - external_network
      - internal_network
    depends_on:
      - redis
    volumes:
      - /data/config.yaml:/app/data/config.yaml:ro
      - /data:/app/data
    ports:
      - "127.0.0.1:6008:6008"
    healthcheck:
      test: curl --silent --fail localhost:6008/health || exit 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:7-alpine
    container_name: BangumiTelegramBot-redis
    restart: always
    networks:
      - internal_network
    volumes:
      - /data/BangumiTelegramBot/redis:/data
    healthcheck:
      test: redis-cli ping
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  external_network:
  internal_network:
    internal: true
