name: docker

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: misc/Dockerfile
        push: true
        pull: true
        tags: ghcr.io/${{ github.repository_owner }}/BangumiTelegramBot
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/BangumiTelegramBot
        cache-to: type=inline
