name: docker

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Prepare Docker Repo Name
      run: |
        echo "REPO=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.REPO }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: misc/Dockerfile
        push: true
        pull: true
        tags: ghcr.io/${{ env.REPO }}/BangumiTelegramBot
        cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}/BangumiTelegramBot
        cache-to: type=inline
